<?php

/**
 * PluginaExGoogleMapSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginaExGoogleMapSlotTable extends aSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginaExGoogleMapSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginaExGoogleMapSlot');
    }
}